# Generated by Django 3.2.25 on 2025-11-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='application_id',
            field=models.CharField(default='A000000000', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
