# Generated by Django 3.2.25 on 2025-11-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20251114_0037'),
        ('credit', '0003_alter_creditapplication_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_applications', to='products.product'),
        ),
    ]
