# Generated by Django 3.2.25 on 2025-11-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='about_profiles/'),
        ),
    ]
