# Generated by Django 3.2.25 on 2025-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='condition',
            field=models.CharField(default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
