# Generated by Django 3.2.25 on 2025-11-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20251113_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessory_type',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External'), ('Engine', 'Engine'), ('Others', 'Others')], default='Others', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Cars', 'Cars'), ('Accessories', 'Accessories')], default='Cars', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
